// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB80CUkMDyl0lzImAnBI6rIgQB-cnn1NNE',
    appId: '1:332165335135:web:d724e0ccd63299391a73ea',
    messagingSenderId: '332165335135',
    projectId: 'taskmanager-4a102',
    authDomain: 'taskmanager-4a102.firebaseapp.com',
    storageBucket: 'taskmanager-4a102.firebasestorage.app',
    measurementId: 'G-TFMY6BVJZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsqTfQFjUFRHX1Jy3614hiFX0KzIBQ740',
    appId: '1:332165335135:android:61f93f41bb2739211a73ea',
    messagingSenderId: '332165335135',
    projectId: 'taskmanager-4a102',
    storageBucket: 'taskmanager-4a102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg_rRtWnX0gnQLFptt_7SyUvwXIVbLbkQ',
    appId: '1:332165335135:ios:983116e44a43c0731a73ea',
    messagingSenderId: '332165335135',
    projectId: 'taskmanager-4a102',
    storageBucket: 'taskmanager-4a102.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg_rRtWnX0gnQLFptt_7SyUvwXIVbLbkQ',
    appId: '1:332165335135:ios:983116e44a43c0731a73ea',
    messagingSenderId: '332165335135',
    projectId: 'taskmanager-4a102',
    storageBucket: 'taskmanager-4a102.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB80CUkMDyl0lzImAnBI6rIgQB-cnn1NNE',
    appId: '1:332165335135:web:863b86552ad68e611a73ea',
    messagingSenderId: '332165335135',
    projectId: 'taskmanager-4a102',
    authDomain: 'taskmanager-4a102.firebaseapp.com',
    storageBucket: 'taskmanager-4a102.firebasestorage.app',
    measurementId: 'G-LP6C51WW7M',
  );
}
